# Generated by Django 5.2.4 on 2025-07-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=100, unique=True, verbose_name='Зав. № машины')),
                ('engine_number', models.CharField(max_length=100, verbose_name='Зав. № двигателя')),
                ('transmission_number', models.CharField(max_length=100, verbose_name='Зав. № трансмиссии')),
                ('driving_axle_number', models.CharField(max_length=100, verbose_name='Зав. № ведущего моста')),
                ('steering_axle_number', models.CharField(max_length=100, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(blank=True, verbose_name='Комплектация (доп. опции)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
