# Generated by Django 5.2.4 on 2025-07-31 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('references', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='machine',
            name='driving_axle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.drivingaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.machinemodel', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'role': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
    ]
