# Generated by Django 5.2.4 on 2025-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_remove_claim_organization_claim_service_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-failure_date'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='downtime',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Время простоя техники'),
        ),
    ]
