# Generated by Django 5.2.4 on 2025-12-09 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claim_options_alter_claim_downtime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Сервисная организация'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сервисная организация'),
        ),
    ]
