# Generated by Django 5.2.4 on 2025-07-31 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_time', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=100, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.maintenancetype', verbose_name='Вид ТО')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.maintenanceorganization', verbose_name='Организация, проводившая ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
            },
        ),
    ]
