# Generated by Django 5.2.4 on 2025-08-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_servicecompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCompany',
        ),
    ]
